# Generated by Django 4.2.13 on 2024-07-23 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myvet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myvet.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateTimeField(verbose_name='application date')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myvet.pet')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myvet.vaccinetype')),
            ],
        ),
    ]
