# Generated by Django 4.2.13 on 2024-07-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0002_vaccinetype_vaccine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="adress",
            new_name="address",
        ),
    ]
