# Generated by Django 4.2.13 on 2024-07-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0003_rename_adress_user_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="vaccines",
        ),
        migrations.AlterField(
            model_name="vaccine",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vaccines_list",
                to="myvet.pet",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="vaccines",
            field=models.ManyToManyField(
                max_length=1000, null=True, related_name="pets_list", to="myvet.vaccine"
            ),
        ),
    ]
