# Generated by Django 4.2.13 on 2024-07-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0004_remove_pet_vaccines_alter_vaccine_pet_pet_vaccines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="vaccines",
            field=models.ManyToManyField(
                blank=True, related_name="pet_vaccines", to="myvet.vaccine"
            ),
        ),
        migrations.AlterField(
            model_name="vaccine",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myvet.pet"
            ),
        ),
    ]
