# Generated by Django 4.2.13 on 2024-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0007_remove_pet_vaccines_pet_vaccines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="vaccines",
        ),
        migrations.AddField(
            model_name="pet",
            name="vaccines",
            field=models.JSONField(null=True),
        ),
    ]
