# Generated by Django 4.2.13 on 2024-07-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0008_remove_pet_vaccines_pet_vaccines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date published"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date published"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date published"
            ),
        ),
        migrations.AlterField(
            model_name="vaccine",
            name="app_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="application date"
            ),
        ),
    ]
