export const products = [
  {
    id: 1,
    name: "MEGA Alimento Perro",
    description:
      "Super mega alimento para tu perro hambriento. Le da mucha energía y nutrientes para que pueda desarrollarse correctamente.",
    quantity: 50,
    price: 350,
    type: 1,
    pet_type: 1,
    img: "/products/mega-alimento-perro.jpg",
  },
  {
    id: 2,
    name: "MEGA Alimento Gatos",
    description: "El mejor alimento para tu gato.",
    quantity: 30,
    price: 150,
    type: 1,
    pet_type: 2,
    img: "/products/mega-alimento-perro.jpg",
  },
  {
    id: 3,
    name: "Alimento Ultra Caro",
    description: "El que comen las mascotas de Caro Pardíaco",
    quantity: 10,
    price: 1050,
    type: 1,
    pet_type: 1,
    img: "/products/mega-alimento-perro.jpg",
  },
  {
    id: 4,
    name: "Traje Spiderman",
    description: "superhero intensifies",
    quantity: 5,
    price: 15000,
    type: 2,
    pet_type: 2,
    img: "/products/traje-spiderman.jpg",
  },
  {
    id: 5,
    name: "El polar de la abuela",
    description:
      "hecho por las mejores abuelas del universo. Ideal para gatitos muy pelados",
    quantity: 10,
    price: 25000,
    type: 2,
    pet_type: 1,
    img: "/products/traje-spiderman.jpg",
  },
  {
    id: 6,
    name: "Collar anti-idiotas",
    description: "El nombre lo dice todo",
    quantity: 3,
    price: 5000,
    type: 2,
    pet_type: 2,
    img: "/products/traje-spiderman.jpg",
  },
];
